services:
  mongodb:
    image: mongo:latest
    container_name: Api-Generar-Chat
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat4321
    ports:
      - "27027:27017"
    volumes:
      - ./mongodb_data:/data/db
