services:
  mongodb:
    image: mongo:latest
    container_name: Api-Usuarios
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuarios
      MONGO_INITDB_ROOT_PASSWORD: user4321
    ports:
      - "27025:27017"
    volumes:
      - ./mongodb_data:/data/db
