services:
  mongodb:
    image: mongo:latest
    container_name: Api-Salas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: salas
      MONGO_INITDB_ROOT_PASSWORD: salas4321
    ports:
      - "27026:27017"
    volumes:
      - ./mongodb_data:/data/db
